"""empty message

Revision ID: 4cb99e89dfc5
Revises: 
Create Date: 2023-02-19 02:36:05.329922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb99e89dfc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(), nullable=False),
    sa.Column('href', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostel', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('nutrition', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('conditions_for_organizations', sa.String(), nullable=True),
    sa.Column('conditions_for_students', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('science',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(), nullable=False),
    sa.Column('lab', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('description_of_organization', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotelrates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('bed_count', sa.String(), nullable=False),
    sa.Column('count', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotelservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotelservices')
    op.drop_table('hotelrates')
    op.drop_table('science')
    op.drop_table('news')
    op.drop_table('hotel')
    op.drop_table('event')
    # ### end Alembic commands ###
