"""empty message

Revision ID: 527ea4ece14c
Revises: 5c69e29e6931
Create Date: 2023-02-19 07:29:03.690359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '527ea4ece14c'
down_revision = '5c69e29e6931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('track',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('href',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('picture_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('organization',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('hotelrates', schema=None) as batch_op:
        batch_op.alter_column('room_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('bed_count',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('count',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('hotelservices', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('imgs_refs',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('imgs_refs',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    with op.batch_alter_table('travel', schema=None) as batch_op:
        batch_op.alter_column('fio',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('guest_count',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('entry',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('depart',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('hostel_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('hostel_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('depart',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('entry',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('guest_count',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('fio',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('imgs_refs',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('imgs_refs',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('hotelservices', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('hotelrates', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('count',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('bed_count',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('room_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('organization',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('picture_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('href',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('track',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
