"""empty message

Revision ID: 5fed748888ba
Revises: 0c08f73fe69c
Create Date: 2023-02-19 06:25:09.419323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fed748888ba'
down_revision = '0c08f73fe69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('experience',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('family_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ref_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('notifications',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('notifications',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('ref_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('family_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('experience',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
