"""empty message

Revision ID: db8bca7d37ef
Revises: 527ea4ece14c
Create Date: 2023-02-19 07:53:50.500920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8bca7d37ef'
down_revision = '527ea4ece14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotelrates', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('hotelservices', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('hotelservices', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('hotelrates', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
