"""empty message

Revision ID: de1e52650b9a
Revises: f14664c1fcf5
Create Date: 2023-02-18 17:34:55.232951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1e52650b9a'
down_revision = 'f14664c1fcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newstag')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(), nullable=True))
        batch_op.alter_column('href',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('picture_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('picture_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('href',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('tags')

    op.create_table('newstag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name='newstag_news_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='newstag_pkey')
    )
    # ### end Alembic commands ###
